version: '3.9'

services:

  proxy:
    image: nginx:1.24.0
    container_name: speedtest_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - speedtest
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: proxy
    networks:
      - lan

  speedtest:
    build:
      context: ./speedtest
      dockerfile: Dockerfile
    image: php-fpm
    depends_on:
      - postgresql
    environment:
      - TELEMETRY=true
      - TITLE=test
      - MODE=frontend
      - PASSWORD=password
      - ENABLE_ID_OBFUSCATION=true
      - REDACT_IP_ADDRESSES=false
      - DB_TYPE=postgresql
      - DB_NAME=speedtest
      - DB_HOSTNAME=postgresql
      - DB_USERNAME=root
      - DB_PASSWORD=password
    volumes:
      - ./speedtest/servers.json:/servers.json
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: speedtest
    networks:
      - lan

  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "speedtest"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
        - db_data:/var/lib/postgresql/data
        - ./speedtest/results/telemetry_postgresql.sql:/docker-entrypoint-initdb.d/telemetry_postgresql.sql
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: postgresql

    networks:
      - lan

networks:
  lan:
    external: true

volumes:
  db_data:
