---
version: '3.8'

services:
  app:
    build: speedtest/.
    container_name: speedtest_app
    environment:
      - TELEMETRY=${TELEMETRY}
      - TITLE=${TITLE}
      - MODE=${MODE}
      - PASSWORD=${PASSWORD}
      - ENABLE_ID_OBFUSCATION=${ENABLE_ID_OBFUSCATION}
      - REDACT_IP_ADDRESSES=${REDACT_IP_ADDRESSES}
      - DB_TYPE=${DB_TYPE}
      - DB_NAME=${DB_NAME}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT}
    volumes:
      - ./speedtest/docker/servers.json:/speedtest/servers.json
    depends_on:
      - db
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}
        tag: app
    networks:
      - lan
    expose:
      - "80"

  db:
    image: postgres:16
    container_name: speedtest_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./speedtest/results/telemetry_postgresql.sql:/docker-entrypoint-initdb.d/telemetry_postgresql.sql
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}
        tag: db
    networks:
      - lan

  proxy:
    image: nginx:1.24.0
    container_name: speedtest_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./speedtest:/var/www/html/speedtest:ro
    depends_on:
      - app
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}
        tag: proxy
    networks:
      - lan

networks:
  lan:
    external: true
    name: lan

volumes:
  db_data:
