---
version: '3.8'

services:
  app:
    build: speedtest/.
    container_name: speedtest_app
    environment:
      - TELEMETRY=true
      - TITLE=test
      - MODE=frontend
      - PASSWORD=password
      - ENABLE_ID_OBFUSCATION=true
      - REDACT_IP_ADDRESSES=false
      - DB_TYPE=postgresql
      - DB_NAME=speedtest
      - DB_HOSTNAME=postgresql
      - DB_USERNAME=root
      - DB_PASSWORD=password
    volumes:
      - ./speedtest/docker/servers.json:/speedtest/servers.json
    depends_on:
      - db
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: app
    networks:
      - lan
    expose:
      - "80"

  db:
    image: postgres:16
    container_name: speedtest_db
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "speedtest"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./speedtest/results/telemetry_postgresql.sql:/docker-entrypoint-initdb.d/telemetry_postgresql.sql
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: db
    networks:
      - lan

  proxy:
    image: nginx:1.24.0
    container_name: speedtest_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./speedtest:/var/www/html/speedtest:ro
    depends_on:
      - app
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: proxy
    networks:
      - lan

networks:
  lan:
    external: true
    name: lan

volumes:
  db_data:
