---
version: '3.8'

services:
  fluentd:
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    image: final_fluentd
    depends_on:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:24224/api/plugins.json"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    networks:
      - lan

  elasticsearch:
    image: elasticsearch:8.16.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 9200:9200
    networks:
      - lan

  kibana:
    image: kibana:8.16.3
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # Исправлено
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5601
      - NODE_OPTIONS=--max-old-space-size=512
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - lan

networks:
  lan:
    external: true
